# Generated by Django 4.2 on 2023-05-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzivatele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=100, verbose_name='Příjmení')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('heslo', models.CharField(max_length=100, verbose_name='Heslo')),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True)),
                ('datum_posledniho_prihlaseni', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Uživatel banky',
                'verbose_name_plural': 'Uživatelé banky',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Ucty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_uctu', models.CharField(max_length=20, unique=True)),
                ('zustatek', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banka_app.uzivatele')),
            ],
            options={
                'verbose_name': 'Účet',
                'verbose_name_plural': 'Účty',
                'ordering': ['cislo_uctu'],
            },
        ),
        migrations.CreateModel(
            name='Pohyby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('typ_pohybu', models.CharField(max_length=100)),
                ('ucty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banka_app.ucty')),
            ],
            options={
                'verbose_name': 'Pohyb',
                'verbose_name_plural': 'Pohyby',
                'ordering': ['datum'],
            },
        ),
    ]
