# Generated by Django 4.2 on 2023-05-21 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banka_app', '0002_alter_uzivatele_heslo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prevody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('typ_prevodu', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Převod',
                'verbose_name_plural': 'Převody',
                'ordering': ['datum'],
            },
        ),
        migrations.AlterModelOptions(
            name='ucty',
            options={'ordering': ['uzivatel'], 'verbose_name': 'Účet', 'verbose_name_plural': 'Účty'},
        ),
        migrations.AlterModelOptions(
            name='uzivatele',
            options={'ordering': ['prijmeni'], 'verbose_name': 'Uživatel banky', 'verbose_name_plural': 'Uživatelé banky'},
        ),
        migrations.DeleteModel(
            name='Pohyby',
        ),
        migrations.AddField(
            model_name='prevody',
            name='cilovy_ucet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prevod_do', to='banka_app.ucty'),
        ),
        migrations.AddField(
            model_name='prevody',
            name='zdrojovy_ucet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prevod_od', to='banka_app.ucty'),
        ),
    ]
