# Generated by Django 4.2 on 2023-05-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banka_app', '0003_prevody_alter_ucty_options_alter_uzivatele_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucty',
            name='cislo_uctu',
            field=models.CharField(max_length=20, unique=True, verbose_name='Číslo účtu'),
        ),
        migrations.AlterField(
            model_name='ucty',
            name='uzivatel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banka_app.uzivatele', verbose_name='Uživatel'),
        ),
        migrations.AlterField(
            model_name='ucty',
            name='zustatek',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Zůstatek na účtu'),
        ),
    ]
