# Generated by Django 4.2 on 2023-05-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadej označení žánru', max_length=30, verbose_name='Název žánru')),
            ],
            options={
                'verbose_name': 'Žánr',
                'verbose_name_plural': 'Žánry',
                'ordering': ['name'],
            },
        ),
    ]
