# Generated by Django 4.2.1 on 2023-05-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapely', '0003_kapela_pocet_clenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narodnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadej název státu', max_length=30, verbose_name='Název státu')),
            ],
            options={
                'verbose_name': 'Národnost',
                'verbose_name_plural': 'Národnosti',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='kapela',
            name='narodnost',
        ),
        migrations.AddField(
            model_name='kapela',
            name='narodnost',
            field=models.ManyToManyField(to='kapely.narodnost'),
        ),
    ]
