# Generated by Django 4.2 on 2023-05-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapely', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kapela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'Název kapely musí být vyplněn'}, help_text='Zadejte název kapely', max_length=50, verbose_name='Název kapely')),
                ('narodnost', models.CharField(blank=True, help_text='Název státu ze kterého kapela pochází', max_length=50, null=True, verbose_name='Národnost')),
                ('zanr', models.ManyToManyField(to='kapely.zanr')),
            ],
            options={
                'verbose_name': 'Kapela',
                'verbose_name_plural': 'Kapely',
                'ordering': ['name'],
            },
        ),
    ]
