# Generated by Django 4.2 on 2023-05-10 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapely', '0002_kapela'),
    ]

    operations = [
        migrations.AddField(
            model_name='kapela',
            name='pocet_clenu',
            field=models.PositiveIntegerField(blank=True, help_text='Zadejte počet stran (max.100)', null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Počet stran'),
        ),
    ]
