# Generated by Django 4.2.1 on 2023-05-20 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapely', '0004_narodnost_remove_kapela_narodnost_kapela_narodnost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clenove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadej jméno', max_length=50, verbose_name='Name')),
                ('surname', models.CharField(help_text='Zadej příjmení', max_length=50, verbose_name='Surname')),
                ('birth_date', models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Datum narození')),
                ('kapela_type', models.CharField(blank=True, choices=[('bubenik', 'Bubenik'), ('zpevak', 'Zpevak'), ('kytarista', 'Kytarista'), ('baskytarista', 'Baskytarista'), ('klavirista', 'Klavirista')], help_text='Vypber roli', max_length=50, verbose_name='Role v kapele')),
            ],
            options={
                'ordering': ['-birth_date', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='kapela',
            name='pocet_clenu',
            field=models.PositiveIntegerField(blank=True, help_text='Zadejte počet členů', null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Počet členů'),
        ),
    ]
