# Generated by Django 4.2.1 on 2023-05-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapely', '0005_clenove_alter_kapela_pocet_clenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clenove',
            options={'ordering': ['-birth_date', 'name'], 'verbose_name': 'Člen', 'verbose_name_plural': 'Členové'},
        ),
        migrations.AlterField(
            model_name='clenove',
            name='birth_date',
            field=models.DateField(blank=True, help_text='DD-MM-YYYY</em>.', null=True, verbose_name='Datum narození'),
        ),
        migrations.DeleteModel(
            name='Kapela',
        ),
    ]
