# Generated by Django 4.2.1 on 2023-05-20 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapely', '0006_alter_clenove_options_alter_clenove_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kapela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'Název kapely musí být vyplněn'}, help_text='Zadejte název kapely', max_length=50, verbose_name='Název kapely')),
                ('pocet_clenu', models.PositiveIntegerField(blank=True, help_text='Zadejte počet členů', null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Počet členů')),
                ('clenove', models.ManyToManyField(to='kapely.clenove')),
                ('narodnost', models.ManyToManyField(to='kapely.narodnost')),
                ('zanr', models.ManyToManyField(to='kapely.zanr')),
            ],
            options={
                'verbose_name': 'Kapela',
                'verbose_name_plural': 'Kapely',
                'ordering': ['name'],
            },
        ),
    ]
