# Generated by Django 4.2.1 on 2023-05-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapely', '0007_kapela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kapela',
            name='narodnost',
        ),
        migrations.AddField(
            model_name='clenove',
            name='narodnost',
            field=models.ManyToManyField(to='kapely.narodnost'),
        ),
    ]
